### PR TITLE
include 'other' gender in the summary of what's in the data

### PR DESCRIPTION
**Pull request by davewhiteland**
Bring the example into line with what we're actually doing in the data

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
passing back without review as travis is failing

**Comment by davewhiteland** [comment]
Mea culpa (actually as we've just dicussed in RL, I was doing this very wrongly including but not limited to: not following the instructions in the README).

Gemfile.lock updated now, and travis now happy, back to you @tmtmtmtm  -- thanks!

**Comment by davewhiteland** [comment]
@tmtmtmtm see commit message on #35d660eef -- this now simply adds "currently" to the values: hence "currently `male` or `female`".

**Comment by tmtmtmtm** [comment]
I've rebased this, and done a fresh `bundle install`

**Review by tmtmtmtm — APPROVED** [review]

**Pull request merged**
