### PR TITLE
fixed three links to specific code lines in github

### LINKED ISSUE #5: Don't link to individual lines of a file in `master`
http://docs.everypolitician.org/sources.html links directly to https://github.com/everypolitician/everypolitician-data/blob/master/data/Australia/Representatives/sources/instructions.json#L3-L9 and https://github.com/everypolitician/everypolitician-data/blob/master/data/Australia/Representatives/sources/instructions.json#L78-L86

If this file changes, these links could very easily drift out of date, so it would be better to link to the version at a specific sha (when viewing those pages 'y' will take you to the current version)

### PR DESCRIPTION
**Pull request by davewhiteland**
In each case I've picked the latest current commit

Also switched the "one" and "another" `href` values around because these links were actually pointing to each other's (i.e., wrong) examples.

Closes #5

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
:+1:  — thanks @davewhiteland 

There's a nasty travis failure that looks like it's due to the Gemfile being out of sync. I doubt I'll have time to fix that up today, but if this isn't something you can puzzle out yourself, I should hopefully have time to look at it tomorrow.

**Comment by tmtmtmtm** [comment]
If I'm understanding this correctly, it looks like it's because commit a096a5d updated `Gemfile.lock` without the corresponding `Gemfile`. We didn't notice it then because we were _expecting_ the tests to fail, whereas they stand out more here. The `Gemfile.lock` I committed here is generated from the prior Gemfile, and thus presumably out of date, so we should get @chrismytton to redo his earlier upgrade before merging this.

**Comment by tmtmtmtm** [comment]
Ah, no, that's complete nonsense. Ignore everything I just said. I've no idea what went wrong here…

**Comment by chrismytton** [comment]
The reason `Gemfile.lock` keeps changing is [the `Gemfile` is set to use whatever version of Jekyll GitHub uses](https://github.com/everypolitician/everypolitician-docs/blob/6562613e66291bff7dab46a0869265cd235ab464/Gemfile#L5-L7). This is the [recommended approach](http://jekyllrb.com/docs/github-pages/#deploying-jekyll-to-github-pages) but we can change it if it's annoying?

**Comment by davewhiteland** [comment]
I don't mind, once I know what's going on and understand what to do to remedy it :-)

Is the point that these dependencies (e.g., Gem version numbers) _keep_ changing, because the `github-pages` gem is frequently being updated?  And/or that I am failing to update the Gemfile at my end?

**Comment by chrismytton** [comment]
> because the github-pages gem is frequently being updated

[Yes, it's been updated a lot recently](https://rubygems.org/gems/github-pages/versions).

**Comment by davewhiteland** [comment]
OK, that's all good. So I will do `bundle update` often, which is all fine...

...although _conceptually_ it seems a bit uglypugly to be adding this jekyll-wide update into a feature branch --  perhaps better to update the Gemmy stuff in `gh-pages` and then rebase off that? (this a general policy question since we're having the conversation here)

**Comment by chrismytton** [comment]
> perhaps better to update the Gemmy stuff in gh-pages and then rebase off that

In the future this is probably best, but I think it's fine to merge this as-is, at least the `Gemfile.lock` was updated in a separate commit :)

**Pull request merged**
